### ISSUE TITLE
New channel tour - directory, apps and help need visual adjustment

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/redmatrix-addons#6]
Tour is a nice addon for new users, taking them through each icon with a short explanation. The explanation box works fine on a PC till it gets to the icons for directory, apps and help on the right of the screen. 

The left edge of the rectangular box is just underneath the icon it is explaining, thus when the tour gets to the icons for directory, apps and help on the right, the box is obscured, extending beyond the screens right hand side.

Suggstion: make the box not go outside the screen.

https://github.com/redmatrix/redmatrix-addons/tree/master/tour

**Comment by jeroenpraat** [comment]
@HaakonME Can you please close this issue (I somehow can't)? When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla-addons/issues).
